server:
  port: 8088
spring:
  application:
    name: cart-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
      prefer-ip-address: true
      ip-address: 127.0.0.1
ly:
  jwt:
    pubKeyPath: D://rsa/id_rsa.pub
    cookieName: LY_TOKEN